version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  ignore:
      # See:
      # https://github.com/chanzuckerberg/aws-oidc/pull/362
      # https://github.com/chanzuckerberg/aws-oidc/pull/422
      - dependency-name: "github.com/zalando/go-keyring"
