before:
  hooks:
    - make clean

builds:
  - binary: aws-oidc
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags:
      - '-w -s -X github.com/chanzuckerberg/aws-oidc/pkg/util.GitSha={{.Commit}} -X github.com/chanzuckerberg/aws-oidc/pkg/util.Version={{.Version}} -X github.com/chanzuckerberg/aws-oidc/pkg/util.Dirty=false -X github.com/chanzuckerberg/aws-oidc/pkg/util.Release=true'

dockers:
  - dockerfile: Dockerfile
    image_templates:
      - docker.pkg.github.com/chanzuckerberg/aws-oidc/aws-oidc:v{{.Version}}
    extra_files:
      - cmd
      - pkg
      - go.mod
      - go.sum
      - main.go

archives:
  - files:
      - none*

release:
  prerelease: false

brews:
  - description: 'A command line utility tool to help generate AWS STS credentials from an OIDC application.'
    github:
      owner: chanzuckerberg
      name: homebrew-tap
    homepage: 'https://github.com/chanzuckerberg/aws-oidc'
    test: system "#{bin}/aws-oidc version"

env_files:
  github_token: ~/.config/goreleaser/github_token
