builds:
  - binary: aws-oidc
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-w -s -X github.com/chanzuckerberg/aws-oidc/pkg/util.ReleaseGitSha={{.Commit}} -X github.com/chanzuckerberg/aws-oidc/pkg/util.ReleaseVersion={{.Version}}"
    flags:
      - -trimpath

release:
  github:
    owner: chanzuckerberg
    name: aws-oidc

brews:
  - description: "A command line utility tool to help generate AWS STS credentials from an OIDC application."
    tap:
      owner: chanzuckerberg
      name: homebrew-tap
    homepage: "https://github.com/chanzuckerberg/aws-oidc"
    test: system "#{bin}/aws-oidc"
