builds:
  - binary: aws-oidc-rc
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - '-w -s -X github.com/chanzuckerberg/aws-oidc/pkg/util.GitSha={{.Commit}} -X github.com/chanzuckerberg/aws-oidc/pkg/util.Version={{.Version}} -X github.com/chanzuckerberg/aws-oidc/pkg/util.Dirty=false -X github.com/chanzuckerberg/aws-oidc/pkg/util.Release=true'

dockers:
  - dockerfile: Dockerfile
    image_templates:
      - docker.pkg.github.com/chanzuckerberg/aws-oidc/aws-oidc:{{.ShortCommit}}
    extra_files:
      - cmd
      - pkg
      - go.mod
      - go.sum
      - main.go

nfpms:
  - vendor: Chan Zuckerberg Initiative, LLC
    license: MIT
    description: AWS cli single sign on using OIDC
    formats:
      - deb

release:
  prerelease: true
  github:
    owner: chanzuckerberg
    name: aws-oidc

brews:
  - description: "A command line utility tool to help generate AWS STS credentials from an OIDC application."
    name : "aws-oidc-rc"
    tap:
      owner: chanzuckerberg
      name: homebrew-tap
    homepage: "https://github.com/chanzuckerberg/aws-oidc"
    test: system "#{bin}/aws-oidc version"
