apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aws-oidc.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "aws-oidc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "aws-oidc.selectorLabels" . | nindent 6 }}
{{- if .Values.strategy }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "aws-oidc.selectorLabels" . | nindent 8 }}
      namespace: {{ .Values.namespace }}
    spec:
      {{- range .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ . }}
      {{- end }}
      serviceAccount: {{ include "aws-oidc.serviceAccountName" . }}
      serviceAccountName: {{ include "aws-oidc.serviceAccountName" . }}
      {{- if .Values.automountServiceAccountToken }}
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      restartPolicy: {{ .Values.restartPolicy }}
      schedulerName: {{ .Values.schedulerName }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.container.args }}
          args:
          {{- toYaml . | nindent 10 }}
          {{- end }}
          env:
          {{- range .Values.container.envs }}
          - name: {{ .name }}
            value: {{ .value }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.container.repository }}:{{ .Values.container.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            {{- with .Values.livenessProbe }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            {{- with .Values.readinessProbe }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
