
{{- $fullName := include "aws-oidc.fullname" . -}}

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-{{ $fullName }}-external
spec:
  podSelector:
    matchLabels:
      {{- include "aws-oidc.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  {{- with .Values.networkPolicy.ingressRules }}
  ingress:
  {{- toYaml . | nindent 4 }}
  {{- end }}
