apiVersion: v1
kind: Service
metadata:
  name: {{ include "aws-oidc.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "aws-oidc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "aws-oidc.selectorLabels" . | nindent 4 }}
