{{- if .Values.ingress.enabled -}}
{{- $fullName := include "aws-oidc.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}

apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.ingress.namespace }}
  {{- end }}
  labels:
    {{- include "aws-oidc.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- if .Values.ingress.http }}
  - http:
      {{- range .Values.ingress.http.paths }}
      paths:
      - path: {{ . }}
        backend:
          serviceName: redirect
          servicePort: use-annotation
      {{- end }}
    {{- end }}
  - host: {{ .Values.ingress.host.fqdn }}
    http:
      paths:
      {{- range .Values.ingress.host.paths }}
      - path: {{ . }}
        backend:
          serviceName: {{ $fullName }}
          servicePort: {{ $svcPort }}
      {{- end }}
{{- end }}
