
{{- $fullName := include "aws-oidc.fullname" . -}}

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-{{ $fullName }}-external
  namespace: {{ .Values.namespace }}
spec:
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - port: 80
      protocol: TCP
  podSelector:
    matchLabels:
      {{- include "aws-oidc.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress

