name: goreleaser-release

on:
  create:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Log in to Docker GitHub registry
      run: |
      docker login docker.pkg.github.com -u "${GITHUB_ACTOR}" -p "${GITHUB_TOKEN}"
      env:
      GITHUB_ACTOR: ${{ secrets.CZIBUILDBOT_USERNAME }}
      GITHUB_TOKEN: ${{ secrets.CZIBUILDBOT_GITHUB_KEY }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.CZIBUILDBOT_GITHUB_KEY }}
